M48
; DRILL file {KiCad (6.0.1)} date Sat Apr  2 15:14:48 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-02T15:14:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X100.536Y-49.036
X100.536Y-140.984
X192.484Y-49.036
X192.484Y-140.984
T0
M30
